### ISSUE TITLE
제가 어떤 걸 하면 되나요?

### ISSUE THREAD

**Issue by Pleiadex** [devquint/SKKU_BrotherShip_4#1]
안녕하세요, 

소프트웨어학과 17학번 서성윤입니다.

지난 번 미팅을 참석하지 못했습니다.

그래서 제가 어떤 부분을 맡으면 될지 알고 싶습니다.

그리고 전체적으로 진행상황도 함께 공유해주시면 감사드리겠습니다.

**감사합니다.

서성윤 드림.**

**Comment by pauis** [comment]
일단 두 명이서 모여서 레이아웃 작성 역할분배를 했습니다.
